### ISSUE TITLE
Volunteering for  f18

### ISSUE THREAD

**Issue by choilmto** [functions-conf/contributing#3]
### Name

> Cindy Choi

### Role / Title / Company

> Currently looking for work

### Availability

- [x] I'm available all day _(7:30 AM - 9:00 PM)_
- [ ] I'm only available in the AM _(7:30 AM - 12:00 PM)_
- [ ] I'm only available in the PM _(12:00 PM - 9:00 PM)_
- [ ] Other… (please specify)

### Type of activities you can be involved in

> Everything is already planned, booked and coordinated, we're just looking for humans to help scale at the day of the event

- [x] Ticketing & Check-in
- [x] General Guidance, Q&A
- [x] Usher
- [ ] Security
- [x] Social Media
- [ ] Photography
- [x] Food & Catering Organization
- [ ] Other…

### Additional Comments / Questions?
I am looking forward to hearing from you!

**Comment by ahmadnassri** [comment]
@choilmto hello, if you're still interested in volunteering, please email `ahmad@functions.events` for next steps.
