### ISSUE TITLE
Interested in volunteering

### ISSUE THREAD

**Issue by nataliejpchin** [functions-conf/contributing#4]
### Name

> Natalie Chin

### Role / Title / Company

> Front-end web designer/developer

### Availability

- [ ] I'm available all day _(7:30 AM - 9:00 PM)_
- [x] I'm only available in the AM _(7:30 AM - 12:00 PM)_
- [ ] I'm only available in the PM _(12:00 PM - 9:00 PM)_
- [ ] Other… (please specify)

### Type of activities you can be involved in

> Everything is already planned, booked and coordinated, we're just looking for humans to help scale at the day of the event

- [x] Ticketing & Check-in
- [x] General Guidance, Q&A
- [x] Usher
- [ ] Security
- [x] Social Media
- [ ] Photography
- [ ] Food & Catering Organization
- [ ] Other…

**Comment by ahmadnassri** [comment]
@nataliejpchin hello, if you're still interested in volunteering, please email `ahmad@functions.events` for next steps.
